version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: rust-file-nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
